### ISSUE TITLE
Full name error in register form when not using capital letters should be avoided

### ISSUE THREAD

**Issue by kribac12** [NoroffFEU/agency.noroff.dev#532] opened 2024-01-09 10:41 UTC
In the Full Name input in register-form, user gets unspecific error message when not using capital letters for first name and last name.

- possible to automatically put uppercase in first and last name to avoid frustration and keep the process effective and clean?
- API takes firstname and lastname as two separate fields. Probably uses uppercase to split the Full name input into two fields(the register form only have one input for the whole name).

- Possible solutions:
1) Two inputs (first name, last name), but consider less inputs = less effort for user.
2) Automatically uppercase

<img width="637" alt="Screenshot 2024-01-09 at 11 39 25" src="https://github.com/NoroffFEU/agency.noroff.dev/assets/89196018/5c6167b3-1eef-4946-aef6-0e2051c7136b">

**Comment by kimrm** [comment] 2024-01-09 21:23
Still not sure why it's required to have capital letters. I have tested the API with Postman and it's no problem registering a new user with only lower case letters in firstName and lastName.

The following POST request worked without any errors.

```
// POST - https://agency-api.noroff.dev/users
{
  "firstName": "noroff",
  "lastName": "student test",
  "email": "student123123123@example.com",
  "password": "Password123",
  "avatar": ""
}
```

The validation pattern doesn't indicate that capital letters is required. It validates for groups of words, meaning it has to have at least one space in between the names.
Examples:
Johnjonsen - not valid
johnjonsen - not valid
John Johnsen - valid
john johnsen - valid
john paul johnsen - valid

Maybe the problem here is more about how the validation error message is written?

The unspecified error message is more likely because of an error in the API calling function. It looks like the URL is wrong.

**Comment by mhaarseth** [comment] 2024-01-10 07:56
Seems you have done a good amount of testing here to assure the issue is not actually the use of lower case letters, and I think you are probably right about the bug actually appearing somewhere else. I'm not sure how the URL could be wrong when calling the API if it works when using upper case, though, but maybe I am misunderstanding something.

**Comment by kimrm** [comment] 2024-01-10 08:48
@NoroffFEU/korketrekkeren 

This issue seems to have been solved now by issue 574 and pull request https://github.com/NoroffFEU/agency.noroff.dev/pull/578

Can we confirm this is working now?

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/20448821/5fa0dd89-aa37-48de-83a3-14ac1ddf6992)

**Comment by mhaarseth** [comment] 2024-01-10 09:25
I am able to register with "lowercase lowercase" as the name, but when logging in, I get "Cannot GET /pages/user/index".

**Comment by kimrm** [comment] 2024-01-10 09:57
Thanks! 

The login problem is a separate issue. @kribac12 Should we just close this?

**Closed** 2024-01-11 10:00 UTC
