### ISSUE TITLE
Broken image in navbar

### ISSUE THREAD

**Issue by Noroff-Anders** [NoroffFEU/agency.noroff.dev#491] opened 2024-01-08 17:25 UTC
Broken image in navbar

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/114410771/98edbadf-edeb-4f17-abde-e6bf78423c57)

![bilde](https://github.com/NoroffFEU/agency.noroff.dev/assets/114410771/635de052-62cc-40c2-81cb-c1a2b7dd4ada)

**Comment by thikimyen-nguyen** [comment] 2024-01-08 20:55
I found also missing alt for this image.

**Comment by runeunhjem** [comment] 2024-01-09 10:07
Duplicate of ticket #456

**Comment by Noroff-Anders** [comment] 2024-01-09 13:37
oki, closing this :)

**Closed** 2024-01-09 13:37 UTC
Labels: bug, duplicate
