### ISSUE TITLE
Replace apiPath + dummyApiGetSingel with the actual API URL and endpoint.

### ISSUE THREAD

**Issue by RamtinMoshtagh** [NoroffFEU/agency.noroff.dev#687] opened 2024-01-11 13:00 UTC
refactor singleApplicationTemplate.js to work with actual API instead of the dummy API.

**Comment by AnaCascante** [comment] 2024-01-13 11:39
@RamtinMoshtagh Hi,  if your team is finished and the issue is merged, this can be closed :)

**Closed** 2024-01-19 10:19 UTC
Labels: bug, documentation, invalid
