### ISSUE TITLE
Add "a" & Remove "instead!" from "Not a company/applicant? Register as an/a *** instead!"

### ISSUE THREAD

**Issue by Korny94** [NoroffFEU/agency.noroff.dev#556] opened 2024-01-09 13:06 UTC
At: 

/pages/auth/register/company/index.html
/pages/auth/register/applicant/index.html
/pages/auth/register/index.html

**Comment by KarenJoo** [comment] 2024-01-09 13:28
Could you add our QA as "reviewer" on the PR as I am not able to do it from my stand :)

**Comment by Korny94** [comment] 2024-01-09 13:49
Fixed, thank you!
________________________________
Fra: Karen Jo ***@***.***>
Sendt: tirsdag 9. januar 2024 14:29
Til: NoroffFEU/agency.noroff.dev ***@***.***>
Kopi: Karl Magnus Leonardo Nøkling ***@***.***>; Author ***@***.***>
Emne: Re: [NoroffFEU/agency.noroff.dev] Add "a" & Remove "instead!" from "Not a company/applicant? Register as an/a *** instead!" (Issue #556)


Could you add our QA as "reviewer" on the PR as I am not able to do it from my stand :)

**Comment by AnaCascante** [comment] 2024-01-13 12:10
@Jean-Christoffer  close the issue if the issue is fixed and merged :)

**Closed** 2024-01-13 13:16 UTC
